In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [2]:
X = np.array([
    [1, -1, 2, 3],
    [2, 0, 0, 3],
    [0, 1, -1, 3]
], dtype=np.float64)

In [3]:
scaler = MinMaxScaler(feature_range=(1,5))
scaler.fit(X)

MinMaxScaler(copy=True, feature_range=(1, 5))

In [5]:
print(scaler.data_max_)
print(scaler.data_min_)
print(scaler.data_range_)

[2. 1. 2. 3.]
[ 0. -1. -1.  3.]
[2. 2. 3. 0.]


In [7]:
print(scaler.transform(X))

[[3.         1.         5.         1.        ]
 [5.         3.         2.33333333 1.        ]
 [1.         5.         1.         1.        ]]
